data_collection:
  description: >
    Use search tools to find mentions of {topic} from around {current_date}, then convert search results into valid JSONL format. Each line must be a separate JSON object with: content_text, source_platform, author_handle, timestamp, direct_url, engagement_metrics, and content_type. Extract real data from search results, create at least 10 entries.
  expected_output: >
    A valid JSONL file where each line is a complete JSON object containing real data extracted from search results. Focus on content from around {current_date}. No mock data, no placeholder comments, no incomplete entries.
  agent: data_collector

trend_analysis:
  description: >
    Read 'results/raw_data.jsonl' ONCE, analyze all entries for trends, hashtags, and themes. Do not attempt to read the file multiple times. Create a comprehensive markdown report based on the data you read.
  expected_output: >
    A complete markdown report with trend analysis based on the raw data. Include top hashtags, key themes, viral content, and demographic insights.
  agent: trend_analyzer

sentiment_analysis:
  description: >
    Read 'results/raw_data.jsonl' ONCE, analyze sentiment and emotions in all entries. Do not attempt to read the file multiple times. Create a comprehensive markdown report with sentiment insights.
  expected_output: >
    A complete markdown report with sentiment analysis including overall sentiment percentages, positive/negative themes, emotional drivers, and recommendations.
  agent: sentiment_specialist

insights_generation:
  description: >
    Compile a comprehensive social listening report on {topic}, integrating data from 'results/raw_data.jsonl', 'results/trend_report.md', and 'results/sentiment_report.md' to provide actionable recommendations.
  expected_output: >
    A strategic report containing:
    1. Executive Summary
    2. Social Listening Data Overview
    3. Trend and Topic Analysis
    4. Sentiment Insights
    5. Potential Risks and Opportunities
    6. Strategic Recommendations
    7. Conclusion
  agent: insights_reporter
